---
- name: "Installation de Oh-My-zsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/

- name: "Récupération de github du plugin zsh : zsh-autosuggestions"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: .oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes

- name: "Récupération de github du plugin zsh : zsh-completions"
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: .oh-my-zsh/custom/plugins/zsh-completions
    clone: yes


- name: "Récupération de github du plugin zsh : zsh-syntax-highlighting"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: .oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: "Récupération de github du thème: Powerlevel10K"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: .oh-my-zsh/custom/themes/powerlevel10k

- name: "Remettre les droits correctements au dossier parent .oh-my-zsh"
  file:
    path: /home/yishan/.oh-my-zsh
    owner: yishan
    group: yishan
    recurse: yes
