---
- name: "Installation de Oh-My-zsh"
  shell: yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/
  tags: zsh

- name: "Changement pour l'utilisateur courant du shell bash par zsh"
  become: true
  user:
    name: yishan
    shell: /bin/zsh
  tags: zsh
  

- name: "Récupération de github du plugin zsh : zsh-autosuggestions"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: .oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
  tags: zsh

- name: "Récupération de github du plugin zsh : zsh-completions"
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: .oh-my-zsh/custom/plugins/zsh-completions
    clone: yes
  tags: zsh


- name: "Récupération de github du plugin zsh : zsh-syntax-highlighting"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: .oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: yes
  tags: zsh

- name: "Récupération de github du thème: Powerlevel10K"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: .oh-my-zsh/custom/themes/powerlevel10k
    clone: yes
  tags: zsh

- name: "Remplacement d'informations du fichier de configuration .zshrc"
  lineinfile:
    path: /home/yishan/.zshrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: 
  - { regexp: 'ZSH_THEME="robbyrussell"', line: 'ZSH_THEME="powerlevel10k/powerlevel10k"' }
  - { regexp: 'plugins=\(git\)', line: 'plugins=(zsh-autosuggestions zsh-completions zsh-syntax-highlighting)' }
  tags: zshrc