- name: Post-installation d'Ubuntu
  hosts: all
  tasks:
    - name: Installation des paquets de base
      apt: name={{ item }} update_cache=yes
      with_items:
      - vim
      - zsh
      - terminator
      - tmux
      - tilix
      - ccze
      - htop
      - docker.io
      - docker-compose
      - git
      - curl
      - tree
      - nmap
  
    - name: Installation de Oh-My-ZSH + extensions
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        clone: yes
        update: yes
