---
- name: Installation des paquets / outils
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - zsh
    - tmux
    - tilix
    - ccze
    - htop
    - docker.io
    - docker-compose
    - git
    - curl
    - tree
    - nmap
    - tcpdump
    - fonts-firacode
    - discord
    - brave-browser
    - code
    - virtualbox
    - virtualbox-dkms
    - vlc
    - protonvpn
    - protonvpn-gui
    - wireshark
    - steam
    - lutris
  become: true
  tags: apt