---
- name: Installation des paquets / outils
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - zsh
    - tmux
    - tilix
    - ccze
    - htop
    - docker.io
    - docker-compose
    - git
    - curl
    - tree
    - nmap
    - tcpdump
    - fonts-firacode
  become: true
  tags: apt